from .guessing_game import guessing_game
from .fact import search_fact
from .fact import factorial
from .average import find_average
from .add_func import sum_func
from .timer import timer_func
from .threads_fact import threading_fact
from .threads_fact import compute_chunk
from .decorator_class import ProfileDecorator
