import boreholes

oil_field = boreholes.OilField()
borehole1 = boreholes.GasBorehole(2)
borehole2 = boreholes.InjectionBorehole(3)
borehole3 = boreholes.OilBorehole(3)
oil_field.add_fuel_borehole(borehole1)
oil_field.add_fuel_borehole(borehole2)
oil_field.add_fuel_borehole(borehole3)

print(oil_field.injection_boreholes)
oil_field.pump_water()
oil_field.pump_water()

print(oil_field.water_volume)
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
oil_field.pump_fuel()
print(oil_field.water_volume)
print(oil_field.oil_volume)
print(oil_field.gas_volume)
oil_field.show_boreholes()
print(oil_field.fuel_boreholes[0].speed)

